version: 0.2

env:
  parameter-store:
    DOCKER_REGISTRY_USERNAME: /devsec/docker/username
    DOCKER_REGISTRY_PASSWORD: /devsec/docker/password
    SONAR_TOKEN: /devsec/swiggy/token

phases:
  install:
    runtime-versions:
      java: corretto17
      python: 3.11
    commands:
      - echo "Installing Trivy and SonarQube Scanner..."
      - wget https://github.com/aquasecurity/trivy/releases/latest/download/trivy_0.46.0_Linux-64bit.tar.gz
      - tar zxvf trivy_0.46.0_Linux-64bit.tar.gz
      - mv trivy /usr/local/bin/

  pre_build:
    commands:
      - echo "Performing Trivy file scan..."
      - trivy fs . || true

  build:
    commands:
      - echo "Running tests..."
      - echo "Running SonarQube analysis..."
      - ./gradlew sonarqube
      - echo "Building Docker image..."
      - echo "$DOCKER_REGISTRY_PASSWORD" | docker login -u "$DOCKER_REGISTRY_USERNAME" --password-stdin
      - docker build -t "$DOCKER_REGISTRY_USERNAME/swiggy:latest" .
      - docker push "$DOCKER_REGISTRY_USERNAME/swiggy:latest"

  post_build:
    commands:
      - |
        echo "Build and analysis complete."
        aws ses send-email \
          --from "pranitbhale@gmail.com" \
          --to "pranitbhale@gmail.com" \
          --subject "CodeBuild Status: $CODEBUILD_BUILD_ID" \
          --text "Build status: $CODEBUILD_BUILD_STATUS" \
          --region "us-east-1"

artifacts:
  files:
    - appspec.yaml
