version: 0.2

env:
  parameter-store:
    DOCKER_REGISTRY_USERNAME: /devsec/docker/username
    DOCKER_REGISTRY_PASSWORD: /devsec/docker/password
    SONAR_TOKEN: /devsec/sonarqube/token

phases:
  install:
    runtime-versions:
      python: 3.11
      java: corretto17
    commands:
      - echo "Installing Trivy..."
      - curl -sSL https://github.com/aquasecurity/trivy/releases/latest/download/trivy_0.51.1_Linux-64bit.tar.gz | tar -xz -C /usr/local/bin/
      - chmod +x /usr/local/bin/trivy

  pre_build:
    commands:
      - echo "Logging in to Docker..."
      - echo "$DOCKER_REGISTRY_PASSWORD" | docker login -u "$DOCKER_REGISTRY_USERNAME" --password-stdin
      - echo "Running Trivy file scan..."
      - trivy fs --exit-code 0 --severity MEDIUM,HIGH,CRITICAL .

  build:
    commands:
      - echo "Running SonarQube analysis..."
      - ./gradlew sonarqube \
          -Dsonar.projectKey=swiggy \
          -Dsonar.sources=. \
          -Dsonar.host.url=http://54.174.40.221:9000 \
          -Dsonar.login=$SONAR_TOKEN
      - echo "Building Docker image..."
      - docker build -t swiggy-app .
      - docker tag swiggy-app "$DOCKER_REGISTRY_USERNAME/swiggy-app:latest"

  post_build:
    commands:
      - echo "Pushing Docker image to registry..."
      - docker push "$DOCKER_REGISTRY_USERNAME/swiggy-app:latest"
      - echo "Sending email notification..."
      - aws ses send-email \
          --from "pranitbhale@gmail.com" \
          --to "pranitbhale@gmail.com" \
          --subject "CodeBuild Status: $CODEBUILD_BUILD_ID" \
          --text "Build status: $CODEBUILD_BUILD_STATUS" \
          --region "us-east-1"

artifacts:
  files:
    - appspec.yaml
